# -*- coding: utf-8 -*-
"""ml_middle1106@naver.com

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsKy35IpzmRYfHEuHHt4_b5wDAn5BnJc
"""

!pip install pandas scikit-learn matplotlib
import pandas as pd
import matplotlib.pyplot as plt
#scikit-learn 에서 필요한 도구들을 import 합니다.
from sklearn.tree import DecisionTreeClassifier,plot_tree
#1. 그림과 유사한 구조를 만들기 위한 가상의 타이타닉 데이터 생성
# (실제 데이터가  없어도 코드가 바로 작성하도록 가상 데이터를 만듭니다)
data={
    'sex': [0,1,0,1,0,0,1,1,0,1] * 10, #0:여성,1:남성
    'pclass' : [1,3,2,3,1,3,1,2,3,1] * 10, # 티켓등급(1,2,3)
    'fare': [50,7.25,26,8.05,80,15,51,9,10,200] *10, # 요금 #요금
    'age' : [22,38,26,35,54,2,27,14,4,30] *10,        #나이
    'title': [0,1,0,0,1,0,1,0,0,1] * 10,     # 호칭 정보
    'survived' : [1,0,1,0,1,0,1,0,1,0] * 10  #생존여부(0:사망, 1:생존)
}

df = pd.DataFrame(data)

# 입력 특징(x)과 예측할 대상(y) 분리
X =df[['sex','pclass','fare','age','title']]
y = df['survived']

#2. 의사결정 트리 모델 생성 및 학습
# 그림과 같은 깊이(Depth)를 가지도록 max_depth를 3으로 제한하고,불순도 기준을 entropy로 설정합니다.
model = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)
model.fit(X,y)
# 3. 트리 시각화 설정 및 그리기
# 그림의 크기를 설정합니다 (가로16인치, 세로 8인치)
plt.figure(figsize=(16,8))

# plot_tree 함수를 사용해 그림을 그립니다.
plot_tree(
    model,
    feature_names=X.columns, # 분기 기준에 들어갈 특징 이름들
    class_names=['0','1'],   # 결과 클래스 이름(사망:0,생존:1)
    filled=True,             #노드에 색상을 채워 가독성을 높임
    rounded=True,            #노드 상자의 모서리를 둥글게 설정
    fontsize=10              #글자 크기
)

#4. 이미지 저장 및 화면 출력
plt.savefig('decision_tree_result.png',dpi=300,bbox_inches='tight') # 이미지 파일로 저장
plt.show() # 화면에 그래프 표시