
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree

# 실제 타이타닉 데이터를 URL로부터 로드하고 전처리합니다.
url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
try:
    df = pd.read_csv(url, sep='\t')
    df['sex'] = df['Sex'].map({'male': 1, 'female': 0})
    df['pclass'] = df['Pclass']
    df['fare'] = df['Fare'].fillna(df['Fare'].median())
    df['title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)
    title_mapping = {"Mr": 0, "Miss": 1, "Mrs": 2, "Master": 3}
    df['title'] = df['title'].map(title_mapping).fillna(4)
    df['age'] = df.groupby('title')['Age'].transform(lambda x: x.fillna(x.median()))
    df['age'] = df['age'].fillna(df['Age'].median())
    df['survived'] = df['Survived']
    
    X = df[['sex', 'pclass', 'fare', 'age', 'title']]
    y = df['survived']
    print("실제 타이타닉 데이터를 불러와 학습을 진행합니다!")
except Exception as e:
    print(f"실제 데이터 로드 실패 ({e}). 가상 임시 데이터를 사용합니다.")
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
# -*- coding: utf-8 -*-
"""ml_middle1106@naver.com

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsKy35IpzmRYfHEuHHt4_b5wDAn5BnJc
"""

# !pip install pandas scikit-learn matplotlib


#scikit-learn 에서 필요한 도구들을 import 합니다.

#1. 그림과 유사한 구조를 만들기 위한 가상의 타이타닉 데이터 생성
# (실제 데이터가  없어도 코드가 바로 작성하도록 가상 데이터를 만듭니다)
# 가상 임시 데이터 주석 처리
pass



# 입력 특징(x)과 예측할 대상(y) 분리
X =df[['sex','pclass','fare','age','title']]
y = df['survived']

#2. 의사결정 트리 모델 생성 및 학습
# 그림과 같은 깊이(Depth)를 가지도록 max_depth를 3으로 제한하고,불순도 기준을 entropy로 설정합니다.
model = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)
model.fit(X,y)
# 3. 트리 시각화 설정 및 그리기
# 그림의 크기를 설정합니다 (가로16인치, 세로 8인치)
plt.figure(figsize=(16,8))

# plot_tree 함수를 사용해 그림을 그립니다.
plot_tree(
    model,
    feature_names=X.columns, # 분기 기준에 들어갈 특징 이름들
    class_names=['0','1'],   # 결과 클래스 이름(사망:0,생존:1)
    filled=True,             #노드에 색상을 채워 가독성을 높임
    rounded=True,            #노드 상자의 모서리를 둥글게 설정
    fontsize=10              #글자 크기
)

#4. 이미지 저장 및 화면 출력
plt.savefig('decision_tree_result.png',dpi=300,bbox_inches='tight') # 이미지 파일로 저장
plt.show() # 화면에 그래프 표시