# -*- coding: utf-8 -*-
"""bc_card_middle1106@nave.com.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxu9kggymf2b7xjQQZKvFiVefqKJ-OPQ
"""

import pandas as pd

# ======================================================
# 1. 데이터 불러오기 (Read) - 한글 인코딩 옵션 추가!
# ======================================================
try:
    # 한글 깨짐을 방지하기 위해 encoding='cp949' 옵션을 추가했습니다.
    df_card = pd.read_csv("../data/bc_card.txt", sep='\t', encoding='cp949')
    df_out = pd.read_csv("../data/bc_card_out2020_03.txt", sep='\t', encoding='cp949')
    print("데이터를 성공적으로 불러왔습니다!")
except Exception as e:
    # 만약 cp949로도 안 열리면 euc-kr로 한 번 더 시도하도록 설정
    try:
        df_card = pd.read_csv("../data/bc_card.txt", sep='\t', encoding='euc-kr')
        df_out = pd.read_csv("../data/bc_card_out2020_03.txt", sep='\t', encoding='euc-kr')
        print("데이터를 성공적으로 불러왔습니다! (euc-kr)")
    except Exception as e2:
        print("파일 불러오기 실패! 에러 원인:", e2)
        # 불러오기 실패 시 변수를 확실하게 제거하여 21번 줄 에러 방지
        df_card, df_out = None, None

# ==============================================================
# 2. 데이터 구조 및 칼럼(열) 확인 (Explore)
# ==============================================================
# 변수가 None이 아니고 정상적인 표(DataFrame)일 때만 실행합니다.
if df_card is not None and df_out is not None:
    print("\n[bc_card.txt 데이터 상위 5행]")
    print(df_card.head())

    print("\n[bc_card_out2020_03.txt 데이터 구조 정보]")
    print(df_out.info())

    # ==============================================================
    # 3. 소비 데이터 분석 (Analysis)
    # ==============================================================
    # [분석 1] 업종별 소비 규모 분석
    if '업종' in df_out.columns and '이용금액' in df_out.columns:
        sector_analysis = df_out.groupby('업종')['이용금액'].agg(['sum', 'mean']).sort_values(by='sum', ascending=False)
        print("\n[업종별 소비 금액 합계 및 평균]")
        print(sector_analysis.head(10))

    # [분석 2] 성별 및 연령대별 소비 패턴
    if '성별' in df_out.columns and '연령대' in df_out.columns and '이용금액' in df_out.columns:
        demographic_spending = df_out.groupby(['연령대', '성별'])['이용금액'].sum().unstack()
        print("\n[연령대 및 성별 기준 총 소비액]")
        print(demographic_spending)

    # [분석 3] 일자별 소비 추이
    if '이용일자' in df_out.columns and '이용금액' in df_out.columns:
        daily_trend = df_out.groupby('이용일자')['이용금액'].sum()
        print("\n[일자별 총 소비 추이 (상위 5일)]")
        print(daily_trend.sort_values(ascending=False).head(5))

    # ===================================================
    # 4. 분석 결과 저장하기 (Export)
    # ===================================================
    try:
        if 'sector_analysis' in locals():
            sector_analysis.to_csv('sector_analysis_result.csv', encoding='utf-8-sig')
            print("\n분석 결과가 'sector_analysis_result.csv' 파일로 저장되었습니다.")
    except Exception as e:
        print("결과 저장 실패:", e)

